name: Deploy test-task to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'test-task/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./test-task
        run: npm install

      - name: Build project
        working-directory: ./test-task
        run: npm run build

      - name: Disable Jekyll
        run: touch ./test-task/dist/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./test-task/dist
          publish_branch: gh-pages